import { config } from 'dotenv';
config({ path: '.env' });

import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/admission_db' });

const all24Universities = [
  {
    name: 'Bangladesh University of Engineering and Technology',
    short_name: 'BUET',
    description: 'Premier engineering university in Bangladesh known for rigorous academic excellence in engineering and architecture.',
    location: 'Dhaka',
    website: 'https://buet.ac.bd',
    logo: '🏛️',
    founded_year: 1876,
    admission_type: 'merit',
    cutoff_marks: 450,
    application_window: 'Jan 15, 2026 – Feb 05, 2026',
    test_date: 'Feb 28, 2026',
    min_gpa: 'SSC 4.00, HSC 4.00 (PHY+CHE+MATH: 270 pts)',
    group: 'Science',
    units: 'Ka (Engg), Kha (Arch)',
    seats: 1305,
    status: 'Applications Open',
  },
  {
    name: 'University of Dhaka',
    short_name: 'DU',
    description: 'The oldest and largest public university in Bangladesh with comprehensive faculties.',
    location: 'Dhaka',
    website: 'https://du.ac.bd',
    logo: '🎓',
    founded_year: 1921,
    admission_type: 'merit',
    cutoff_marks: 400,
    application_window: 'Jan 20, 2026 – Feb 15, 2026',
    test_date: 'Mar 08, 2026',
    min_gpa: 'Combined GPA 8.00 (Min 3.50 each)',
    group: 'All Groups',
    units: 'Ka (Sci), Kha (Arts), Ga (BBA), Cha (Fine Arts)',
    seats: 7120,
    status: 'Applications Open',
  },
  {
    name: 'Medical & Dental Colleges (MBBS / BDS Centralized Combined Exam)',
    short_name: 'Medical & Dental (DGHS)',
    description: 'Centralized government medical and dental college admission exam conducted by DGHS.',
    location: 'Nationwide (37 Gov Medical + 12 Dental)',
    website: 'https://dghs.gov.bd',
    logo: '🏥',
    founded_year: 1946,
    admission_type: 'merit',
    cutoff_marks: 280,
    application_window: 'Jan 10, 2026 – Jan 30, 2026',
    test_date: 'Feb 14, 2026',
    min_gpa: 'Total GPA 9.00 (Biology Min 4.00)',
    group: 'Science (Biology)',
    units: 'Central MBBS & BDS Merit List',
    seats: 5380,
    status: 'Applications Open',
  },
  {
    name: 'GST General, Science & Tech Cluster (24 Public Universities)',
    short_name: 'GST 24 Cluster',
    description: 'Unified centralized admission cluster system covering 24 general and STEM public universities across Bangladesh.',
    location: 'Nationwide 24 Universities',
    website: 'https://gstadmission.ac.bd',
    logo: '🌐',
    founded_year: 2020,
    admission_type: 'merit',
    cutoff_marks: 320,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026',
    min_gpa: 'Science: 8.00, Arts: 7.00, Comm: 7.50',
    group: 'All Groups',
    units: 'Unit A (Sci), Unit B (Hum), Unit C (Bus)',
    seats: 21500,
    status: 'Opening Soon',
  },
  {
    name: 'Agriculture 9 Public University Combined Cluster (BAU, BSMRAU, SAU)',
    short_name: 'Agriculture 9 Cluster',
    description: 'Combined admission cluster for agricultural sciences, veterinary, and biotechnology across 9 specialized universities.',
    location: 'Nationwide 9 Agriculture Universities',
    website: 'https://acas.edu.bd',
    logo: '🌾',
    founded_year: 2019,
    admission_type: 'merit',
    cutoff_marks: 350,
    application_window: 'Mar 01, 2026 – Mar 25, 2026',
    test_date: 'May 03, 2026',
    min_gpa: 'Combined GPA 8.50 (Science & Biology)',
    group: 'Science (Biology)',
    units: 'Combined Agricultural Science Merit List',
    seats: 4230,
    status: 'Opening Soon',
  },
  {
    name: 'Jahangirnagar University',
    short_name: 'JU',
    description: 'Only fully residential public university in Bangladesh renowned for natural sciences and social research.',
    location: 'Savar, Dhaka',
    website: 'https://juniv-admission.org',
    logo: '🌳',
    founded_year: 1970,
    admission_type: 'merit',
    cutoff_marks: 380,
    application_window: 'Jan 18, 2026 – Feb 10, 2026',
    test_date: 'Mar 02, 2026 – Mar 12, 2026',
    min_gpa: 'A Unit: 8.50, D Unit: 9.00',
    group: 'All Groups',
    units: 'Unit A, B, C, D (Bio), E',
    seats: 1844,
    status: 'Applications Open',
  },
  {
    name: 'University of Rajshahi',
    short_name: 'RU',
    description: 'Second oldest comprehensive public research university in Bangladesh.',
    location: 'Rajshahi',
    website: 'https://admission.ru.ac.bd',
    logo: '🏛️',
    founded_year: 1953,
    admission_type: 'merit',
    cutoff_marks: 370,
    application_window: 'Jan 08, 2026 – Jan 28, 2026',
    test_date: 'Mar 05, 2026 – Mar 07, 2026',
    min_gpa: 'Unit A: 7.00, Unit B: 7.50, Unit C: 8.00',
    group: 'All Groups',
    units: 'Unit A (Humanities), Unit B (BBA), Unit C (Science)',
    seats: 4173,
    status: 'Applications Open',
  },
  {
    name: 'University of Chittagong',
    short_name: 'CU',
    description: 'Prestigious public university nestled among scenic hills in Chittagong.',
    location: 'Chittagong',
    website: 'https://admission.cu.ac.bd',
    logo: '🌄',
    founded_year: 1966,
    admission_type: 'merit',
    cutoff_marks: 360,
    application_window: 'Jan 12, 2026 – Feb 02, 2026',
    test_date: 'Mar 10, 2026 – Mar 18, 2026',
    min_gpa: 'A Unit: 8.00, B Unit: 7.50, C Unit: 8.00',
    group: 'All Groups',
    units: 'A (Science), B (Arts), C (Business), D (Combined)',
    seats: 4926,
    status: 'Applications Open',
  },
  {
    name: 'Khulna University of Engineering & Technology',
    short_name: 'KUET',
    description: 'Leading engineering and technology research institution in south-western Bangladesh.',
    location: 'Khulna',
    website: 'https://kuet.ac.bd',
    logo: '⚙️',
    founded_year: 1967,
    admission_type: 'merit',
    cutoff_marks: 400,
    application_window: 'Feb 01, 2026 – Feb 22, 2026',
    test_date: 'Mar 15, 2026',
    min_gpa: 'HSC GPA 4.00 (PHY, CHE, MATH min A)',
    group: 'Science',
    units: 'Unit A (Engineering), Unit B (Architecture)',
    seats: 1065,
    status: 'Applications Open',
  },
  {
    name: 'Rajshahi University of Engineering & Technology',
    short_name: 'RUET',
    description: 'Renowned public engineering university in the northern division of Bangladesh.',
    location: 'Rajshahi',
    website: 'https://ruet.ac.bd',
    logo: '🔧',
    founded_year: 1964,
    admission_type: 'merit',
    cutoff_marks: 380,
    application_window: 'Feb 05, 2026 – Feb 25, 2026',
    test_date: 'Mar 22, 2026',
    min_gpa: 'HSC GPA 4.00 (PHY, CHE, MATH min A)',
    group: 'Science',
    units: 'Ka (Engineering), Kha (Planning & Arch)',
    seats: 1230,
    status: 'Applications Open',
  },
  {
    name: 'Chittagong University of Engineering & Technology',
    short_name: 'CUET',
    description: 'Top-tier engineering university situated in Raozan, Chittagong.',
    location: 'Chittagong',
    website: 'https://cuet.ac.bd',
    logo: '🏗️',
    founded_year: 1968,
    admission_type: 'merit',
    cutoff_marks: 380,
    application_window: 'Feb 10, 2026 – Mar 01, 2026',
    test_date: 'Mar 29, 2026',
    min_gpa: 'HSC GPA 4.00 (Math, Physics, Chemistry A)',
    group: 'Science',
    units: 'Ka, Kha',
    seats: 920,
    status: 'Opening Soon',
  },
  {
    name: 'Bangladesh University of Textiles',
    short_name: 'BUTEX',
    description: 'Specialized public university dedicated to textile engineering and polymer technology.',
    location: 'Tejgaon, Dhaka',
    website: 'https://butex.edu.bd',
    logo: '🧵',
    founded_year: 1921,
    admission_type: 'merit',
    cutoff_marks: 390,
    application_window: 'Feb 01, 2026 – Feb 20, 2026',
    test_date: 'Apr 04, 2026',
    min_gpa: 'Total GPA 9.00 (Math, Physics, Chem, Eng: Min A)',
    group: 'Science',
    units: 'Textile Engineering Faculties',
    seats: 600,
    status: 'Opening Soon',
  },
  {
    name: 'Military Institute of Science and Technology',
    short_name: 'MIST',
    description: 'Advanced engineering institution affiliated with BUP located in Mirpur Cantonment.',
    location: 'Mirpur Cantt, Dhaka',
    website: 'https://mist.ac.bd',
    logo: '🛡️',
    founded_year: 1998,
    admission_type: 'merit',
    cutoff_marks: 410,
    application_window: 'Jan 05, 2026 – Jan 25, 2026',
    test_date: 'Feb 20, 2026',
    min_gpa: 'Total GPA 9.00 (Science: PCM min A+)',
    group: 'Science',
    units: 'Engineering & Architecture Units',
    seats: 820,
    status: 'Deadline Passed',
  },
  {
    name: 'Bangladesh University of Professionals',
    short_name: 'BUP',
    description: 'Specialized public university with modern campus in Mirpur Cantonment.',
    location: 'Mirpur Cantt, Dhaka',
    website: 'https://bup.edu.bd',
    logo: '🎖️',
    founded_year: 2008,
    admission_type: 'merit',
    cutoff_marks: 360,
    application_window: 'Jan 02, 2026 – Jan 20, 2026',
    test_date: 'Feb 06, 2026 – Feb 07, 2026',
    min_gpa: 'Combined GPA 8.50 - 9.00 (Faculty based)',
    group: 'All Groups',
    units: 'FST, FBA, FASS, FBS',
    seats: 1450,
    status: 'Deadline Passed',
  },
  {
    name: 'Khulna University',
    short_name: 'KU',
    description: 'General public university recognized for clean politics and academic discipline.',
    location: 'Khulna',
    website: 'https://ku.ac.bd',
    logo: '🎓',
    founded_year: 1991,
    admission_type: 'merit',
    cutoff_marks: 340,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Merit Score Requirement',
    group: 'All Groups',
    units: 'SET, Life Science, Arts, Management',
    seats: 1215,
    status: 'Opening Soon',
  },
  {
    name: 'Shahjalal University of Science and Technology',
    short_name: 'SUST',
    description: 'First specialized science and technology public research university in Bangladesh.',
    location: 'Sylhet',
    website: 'https://sust.edu',
    logo: '🔬',
    founded_year: 1986,
    admission_type: 'merit',
    cutoff_marks: 370,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria (Science min 8.00)',
    group: 'All Groups',
    units: 'A Unit (Science), B Unit (Non-Science)',
    seats: 1700,
    status: 'Opening Soon',
  },
  {
    name: 'Jagannath University',
    short_name: 'JnU',
    description: 'Major historic public university located in Old Dhaka.',
    location: 'Dhaka',
    website: 'https://jnu.ac.bd',
    logo: '🏛️',
    founded_year: 1858,
    admission_type: 'merit',
    cutoff_marks: 330,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Evaluation',
    group: 'All Groups',
    units: 'Science, Humanities, Business Units',
    seats: 2765,
    status: 'Opening Soon',
  },
  {
    name: 'Jashore University of Science and Technology',
    short_name: 'JUST',
    description: 'Leading STEM and biotechnology research university in south-western region.',
    location: 'Jashore',
    website: 'https://just.edu.bd',
    logo: '🧬',
    founded_year: 2007,
    admission_type: 'merit',
    cutoff_marks: 330,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria',
    group: 'Science',
    units: 'Engineering, Bio-science, Health Science',
    seats: 980,
    status: 'Opening Soon',
  },
  {
    name: 'Bangladesh Agricultural University',
    short_name: 'BAU',
    description: 'Premier pioneer agricultural university in South Asia located in Mymensingh.',
    location: 'Mymensingh',
    website: 'https://bau.edu.bd',
    logo: '🌾',
    founded_year: 1961,
    admission_type: 'merit',
    cutoff_marks: 360,
    application_window: 'Mar 01, 2026 – Mar 25, 2026',
    test_date: 'May 03, 2026 (Agriculture Cluster)',
    min_gpa: 'Science GPA 8.50 (Bio, Phy, Chem, Math)',
    group: 'Science (Biology)',
    units: 'Agriculture, Vet Science, Fisheries, Ag-Econ',
    seats: 1110,
    status: 'Opening Soon',
  },
  {
    name: 'Comilla University',
    short_name: 'CoU',
    description: 'Dynamic public university located near Shalban Vihara in Cumilla.',
    location: 'Cumilla',
    website: 'https://cou.ac.bd',
    logo: '🏛️',
    founded_year: 2006,
    admission_type: 'merit',
    cutoff_marks: 310,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria',
    group: 'All Groups',
    units: 'Science, Arts, Commerce Units',
    seats: 1040,
    status: 'Opening Soon',
  },
  {
    name: 'Begum Rokeya University, Rangpur',
    short_name: 'BRUR',
    description: 'Prominent public university situated in Rangpur division.',
    location: 'Rangpur',
    website: 'https://brur.ac.bd',
    logo: '🎓',
    founded_year: 2008,
    admission_type: 'merit',
    cutoff_marks: 300,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria',
    group: 'All Groups',
    units: 'Unit A, B, C, D, E, F',
    seats: 1395,
    status: 'Opening Soon',
  },
  {
    name: 'Mawlana Bhashani Science and Technology University',
    short_name: 'MBSTU',
    description: 'Science and technology university named after legendary leader Mawlana Bhashani.',
    location: 'Santosh, Tangail',
    website: 'https://mbstu.ac.bd',
    logo: '🔬',
    founded_year: 1999,
    admission_type: 'merit',
    cutoff_marks: 320,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria',
    group: 'Science',
    units: 'Engineering, Life Science, Business',
    seats: 865,
    status: 'Opening Soon',
  },
  {
    name: 'Noakhali Science and Technology University',
    short_name: 'NSTU',
    description: 'Coastal science and technology university known for marine biology and software engineering.',
    location: 'Noakhali',
    website: 'https://nstu.edu.bd',
    logo: '🌊',
    founded_year: 2001,
    admission_type: 'merit',
    cutoff_marks: 310,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria',
    group: 'Science',
    units: 'A, B, C, D Units',
    seats: 1450,
    status: 'Opening Soon',
  },
  {
    name: 'Jatiya Kabi Kazi Nazrul Islam University',
    short_name: 'JKKNIU',
    description: 'Public university dedicated to arts, music, social sciences, and technology in Trishal.',
    location: 'Trishal, Mymensingh',
    website: 'https://jkkniu.edu.bd',
    logo: '🎭',
    founded_year: 2006,
    admission_type: 'merit',
    cutoff_marks: 300,
    application_window: 'Feb 15, 2026 – Mar 10, 2026',
    test_date: 'Apr 12, 2026 (Under GST)',
    min_gpa: 'GST Cluster Criteria (Combined GPA 7.00)',
    group: 'All Groups',
    units: 'AL, AP, BBA, Science Faculties',
    seats: 1120,
    status: 'Opening Soon',
  },
];

async function main() {
  console.log('Seeding PostgreSQL database with all 24 universities...');

  for (const u of all24Universities) {
    const res = await pool.query(
      `INSERT INTO universities (name, short_name, description, location, website, logo, founded_year, admission_type, cutoff_marks, metadata)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       ON CONFLICT (short_name) DO UPDATE SET
         name = EXCLUDED.name,
         description = EXCLUDED.description,
         location = EXCLUDED.location,
         website = EXCLUDED.website,
         logo = EXCLUDED.logo,
         metadata = EXCLUDED.metadata
       RETURNING id`,
      [
        u.name,
        u.short_name,
        u.description,
        u.location,
        u.website,
        u.logo,
        u.founded_year,
        u.admission_type,
        u.cutoff_marks,
        JSON.stringify({
          application_window: u.application_window,
          test_date: u.test_date,
          min_gpa: u.min_gpa,
          group: u.group,
          units: u.units,
          seats: u.seats,
          status: u.status,
        }),
      ]
    );

    const uniId = res.rows[0]?.id;
    if (uniId) {
      // Upsert into admission_circulars
      await pool.query(
        `INSERT INTO admission_circulars (university_id, title, unit, year, official_url, summary, requirements)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT DO NOTHING`,
        [
          uniId,
          `${u.short_name} Admission Circular 2026`,
          u.units,
          2026,
          u.website,
          u.description,
          JSON.stringify({
            application_window: u.application_window,
            test_date: u.test_date,
            min_gpa: u.min_gpa,
            group: u.group,
            seats: u.seats,
            status: u.status,
          }),
        ]
      );
    }
  }

  // Create and Seed admission_events table
  await pool.query(`
    CREATE TABLE IF NOT EXISTS admission_events (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      university_id UUID REFERENCES universities(id) ON DELETE CASCADE,
      university_name TEXT NOT NULL,
      unit TEXT,
      event_type TEXT NOT NULL,
      title TEXT NOT NULL,
      event_date TIMESTAMP NOT NULL,
      description TEXT,
      source_url TEXT,
      status TEXT DEFAULT 'upcoming',
      created_at TIMESTAMP DEFAULT NOW() NOT NULL
    );
  `);

  await pool.query(`DELETE FROM admission_events`);

  const eventsData = [
    {
      uniShort: 'BUET',
      unit: 'Ka Unit (Engineering & CS)',
      eventType: 'application_deadline',
      title: 'Application Deadline',
      eventDate: '2026-09-18T23:59:59Z',
      desc: 'Online application window closes for BUET undergraduate programs.',
      url: 'https://buet.ac.bd',
    },
    {
      uniShort: 'BUET',
      unit: 'Preliminary Admission Test',
      eventType: 'exam_date',
      title: 'Preliminary Exam',
      eventDate: '2026-09-28T10:00:00Z',
      desc: 'Shift-wise MCQ preliminary screening test.',
      url: 'https://buet.ac.bd',
    },
    {
      uniShort: 'DU',
      unit: 'Ka Unit (Science)',
      eventType: 'application_deadline',
      title: 'Application Deadline',
      eventDate: '2026-10-05T23:59:59Z',
      desc: 'Dhaka University Ka Unit application portal closes.',
      url: 'https://du.ac.bd',
    },
    {
      uniShort: 'DU',
      unit: 'Ka Unit (Science)',
      eventType: 'exam_date',
      title: 'Ka Unit Admission Test',
      eventDate: '2026-10-25T11:00:00Z',
      desc: 'Written & MCQ combined admission test nationwide at divisional centers.',
      url: 'https://du.ac.bd',
    },
    {
      uniShort: 'Medical & Dental (DGHS)',
      unit: 'MBBS / BDS Combined',
      eventType: 'exam_date',
      title: 'MBBS Admission Test',
      eventDate: '2026-11-14T10:00:00Z',
      desc: 'Centralized 100-mark nationwide MBBS admission exam.',
      url: 'https://dghs.gov.bd',
    },
    {
      uniShort: 'GST 24 Cluster',
      unit: 'A Unit (Science)',
      eventType: 'application_deadline',
      title: 'GST Application Deadline',
      eventDate: '2026-10-15T23:59:59Z',
      desc: 'Single application for 24 public general, science & technology universities.',
      url: 'https://gstadmission.ac.bd',
    },
    {
      uniShort: 'GST 24 Cluster',
      unit: 'A Unit (Science)',
      eventType: 'exam_date',
      title: 'GST Combined Exam',
      eventDate: '2026-11-08T11:00:00Z',
      desc: 'Combined 100-mark MCQ test for all 24 general cluster universities.',
      url: 'https://gstadmission.ac.bd',
    },
    {
      uniShort: 'Agriculture 9 Cluster',
      unit: 'Combined Agricultural Science',
      eventType: 'exam_date',
      title: 'Agriculture Combined Test',
      eventDate: '2026-11-22T11:00:00Z',
      desc: 'Combined admission test for 9 public agricultural universities (BAU, BSMRAU, SAU).',
      url: 'https://acas.edu.bd',
    },
    {
      uniShort: 'BUTEX',
      unit: 'Textile Engineering',
      eventType: 'exam_date',
      title: 'Written Admission Test',
      eventDate: '2026-11-29T10:00:00Z',
      desc: 'Written admission examination for Bangladesh University of Textiles.',
      url: 'https://butex.edu.bd',
    },
    {
      uniShort: 'MIST',
      unit: 'Engineering & Architecture',
      eventType: 'exam_date',
      title: 'MIST Admission Test',
      eventDate: '2026-12-05T09:00:00Z',
      desc: 'Military Institute of Science & Technology undergraduate entrance test.',
      url: 'https://mist.ac.bd',
    },
  ];

  for (const evt of eventsData) {
    const uniRes = await pool.query(`SELECT id, name FROM universities WHERE short_name = $1 LIMIT 1`, [evt.uniShort]);
    const uni = uniRes.rows[0];
    await pool.query(
      `INSERT INTO admission_events (university_id, university_name, unit, event_type, title, event_date, description, source_url, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        uni?.id || null,
        uni?.name || evt.uniShort,
        evt.unit,
        evt.eventType,
        evt.title,
        evt.eventDate,
        evt.desc,
        evt.url,
        'upcoming',
      ]
    );
  }

  const { rows: uniCount } = await pool.query('SELECT COUNT(*) as total FROM universities');
  const { rows: eventCount } = await pool.query('SELECT COUNT(*) as total FROM admission_events');
  console.log(`✓ Successfully seeded PostgreSQL database!`);
  console.log(`  - Total Universities: ${uniCount[0].total}`);
  console.log(`  - Total Admission Deadlines & Events in PostgreSQL: ${eventCount[0].total}`);

  await pool.end();
}

main().catch((err) => {
  console.error('Database seeding error:', err);
  process.exit(1);
});
